spring:
  redis:
    host: 10.211.55.5
    port: 6379

server:
  port: 8086
dubbo:
  consumer:
    check: false
  application:
    name: shop_sso
  registry:
    address: zookeeper://10.211.55.5:2181
  protocol:
    name: dubbo
    port: -1