spring:
  redis:
    host: 10.211.55.5
    port: 6379
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: byesolitia@vip.qq.com
    password: neipmvjipyxybbah
      #port: 587
    test-connection: true

server:
  port: 8086
dubbo:
  consumer:
    check: false
  application:
    name: shop_sso
  registry:
    address: zookeeper://10.211.55.5:2181
  protocol:
    name: dubbo
    port: -1