server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 10.211.55.5
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://10.211.55.5:2181
  protocol:
    port: -1
  consumer:
    check: false