server:
  port: 8083
spring:
  data:
    solr:
      host: http://10.211.55.5:8080/solr
  thymeleaf:
    cache: false
dubbo:
  consumer:
    check: false
  registry:
    address: zookeeper://10.211.55.5:2181
  application:
    name: shop_service