server:
  port: 8089
spring:
  redis:
    host: 10.211.55.5
    port: 6379
  thymeleaf:
    cache: false

dubbo:
  registry:
    address: zookeeper://10.211.55.5:2181
  application:
    name: shop_order
  protocol:
    port: -1
  consumer:
    check: false