server:
  port: 8088
spring:
  redis:
    host: 10.211.55.5
    port: 6379
  thymeleaf:
    cache: false
dubbo:
  consumer:
    check: false
  application:
    name: cart_service
  registry:
    address: zookeeper://10.211.55.5:2181