server:
  port: 8084
spring:
  data:
    solr:
      host: http://10.211.55.5:8080/solr
  thymeleaf:
    cache: false
dubbo:
  registry:
    address: zookeeper://10.211.55.5:2181
  application:
    name: search_service
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false