spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 7MB
server:
  port: 8080
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://10.211.55.5:2181
  consumer:
    check: false
#fdfs
fdfs:
  tracker-list: 10.211.55.5:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  serverpath: http://10.211.55.5/